platform :ios, '9.0'

target 'AwesomeProject' do
    project 'AwesomeProject', 'ReleaseLtvpro' => :release
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        # the following ones are the ones taken from "Libraries" in Xcode:
        'RCTAnimation',
        'RCTActionSheet',
        'RCTBlob',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket'
    ]

     # the following dependencies are dependencies of React native itself.
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'

end

# The following is needed to ensure the "archive" step works in XCode.
# It removes React from the Pods project, as it is already included in the main project.
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
        if target.name == "Pods-AwesomeProject"
            target.build_configurations.each do |config|
                if config.name.start_with?("Release")
                    puts "Updating #{target.name}:#{config.name} OTHER_LDFLAGS"
                    xcconfig_path = config.base_configuration_reference.real_path
                    xcconfig = File.read(xcconfig_path)
                    new_xcconfig = xcconfig.sub('-l"React" ', '')
                    File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
                end
            end
        end
    end
end